discord:
  botToken: "YOUR_BOT_TOKEN"
  channelID: "YOUR_CHANNEL_ID"
  requestAccessChannelID: "YOUR_REQUEST_ACCESS_CHANNEL_ID"
  syncedChannelRoleID: "YOUR_SYNCED_CHANNEL_ROLE_ID"
  commandPrefix: "!"
  serverName: "Book7Shelf"
  statusChannelID: "STATUSCHANNELID"
  statusMessageID: "STATUSMESSAGEID"

integration:
  mincraftChatToDiscord: true
  discordToMinecraftChat: true
  deathMessagesToDiscord: true
  joinQuitMessagesToDiscord: true
  serverStatusChannel: true
  serverSayMessagesToDiscord: true
  advancementsToDiscord: true
  discordWhitelist: true
  serverSayMessageFilterPrefix: '!'
